### ISSUE TITLE
MalwareBytes detected it as malware on Windows 11

### ISSUE THREAD

**Issue by HelloTech2** [ColdWindScholar/MIO-KITCHEN-SOURCE#109]
Detected with this malware
![proof1](https://github.com/user-attachments/assets/e56b2f6a-ffc2-41a4-916b-e5c834504822)
# Solution
Delete it from quarantine, extract all the files again, add the program and `bin` folder to exclusions including the exe

**Comment by HelloTech2** [comment]
It's a false positive?

**Comment by ColdWindScholar** [comment]
> It's a false positive?

Yes, u can check our codes and we not write any malware code or binary
