### ISSUE TITLE
lpunpack is missing

### ISSUE THREAD

**Issue by soralis0912** [ColdWindScholar/MIO-KITCHEN-SOURCE#11]
![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/33514613/168a4ccb-80b2-4636-a468-5ca49692c672)

file is broken diff lpunpack from AOSP

**Comment by ColdWindScholar** [comment]
Zero data is only used for padding, files are normal

**Comment by soralis0912** [comment]
no, but not only Zero padding 

![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/33514613/f8e7eaea-56d1-480e-adce-cc350f52f33b)

**Comment by ColdWindScholar** [comment]
No Problem, If u met some Problem,please the file link to me, thanks!

**Comment by soralis0912** [comment]
ok share link please wait

**Comment by soralis0912** [comment]
https://drive.google.com/file/d/1x2feeTMK2aL0ntHDSscgGuvQZhc1ustx/view?usp=drive_link

this image

file is missing so can't relock bootloader and Cant patch OTA update.

**Comment by ColdWindScholar** [comment]
may no need lpunpack？
