### ISSUE TITLE
打包选择br类型报错

### ISSUE THREAD

**Issue by silentchild** [ColdWindScholar/MIO-KITCHEN-SOURCE#14]
打包选择br类型报错

**Comment by ColdWindScholar** [comment]
好的，朋友，请给我一个截图

**Comment by silentchild** [comment]
![微信截图_20240122105620](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/29771808/f8b145fe-3159-421c-9ebb-e14aa69392e5)
主要是没有错误信息

**Comment by silentchild** [comment]
![Uploading 微信截图_20240122105718.png…]()

**Comment by silentchild** [comment]
就是这样

**Comment by silentchild** [comment]
![微信截图_20240122105718](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/29771808/319e756f-7c87-45f0-943f-cf84511019aa)
就是这样

**Comment by ColdWindScholar** [comment]
Fixed Download 3.1.6 and newer
