### ISSUE TITLE
I tired to repack a boot.img and got the following

### ISSUE THREAD

**Issue by isg32** [ColdWindScholar/MIO-KITCHEN-SOURCE#27]
## I tired to repack a boot.img and got the following:

暂不支持您的设备
Sorry,Not support your device yet.

![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/95901240/37a03995-6a11-4c02-8616-3b7d56216302)

**Comment by ColdWindScholar** [comment]
cd to tool root dir ,then 
```
./tool
```
