### ISSUE TITLE
linux版bug，好几天了，解包ext文件系统的img失败

### ISSUE THREAD

**Issue by ymdzq** [ColdWindScholar/MIO-KITCHEN-SOURCE#3]
正在解包：vendor.img [ext]
Extracting vendor.img --> vendor
Unpack Fail..local variable 'file_target' referenced before assignment

所有product、system、vendor的img都失败，只解压出来两个空文件夹就停止了，系统是manjaro kde最新

另外一个问题，打开rom选择文件那个对话框很难弹出，点半天没反应

**Comment by ColdWindScholar** [comment]
Thanks ,i will fix it

**Comment by ColdWindScholar** [comment]
# Fixed 
## Please Download 2.4.5
