### ISSUE TITLE
error packed package cause crash

### ISSUE THREAD

**Issue by zeng-github01** [ColdWindScholar/MIO-KITCHEN-SOURCE#35]
Value:__name__=__main__
Value:__doc__=None
Value:__package__=None
Value:__loader__=<pyimod02_importers.PyiFrozenImporter object at 0x07146580>
Value:__spec__=None
Value:__annotations__={}
Value:__builtins__=<module 'builtins' (built-in)>
Value:__file__=C:\Users\14337\AppData\Local\Temp\_MEI157962\tool.py
Value:_pyi_main_co=<code object <module> at 0x07CC9500, file "tool.py", line 2>
Value:sys=<module 'sys' (built-in)>
Value:pyimod02_importers=<module 'pyimod02_importers' from 'D:\\MIO\\PyInstaller\\loader\\pyimod02_importers.py'>
Value:os=<module 'os' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\base_library.zip\\os.pyc'>
Value:VIRTENV=VIRTUAL_ENV
Value:python_path=['C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\base_library.zip', 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\lib-dynload', 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962']
Value:pth=C:\Users\14337\AppData\Local\Temp\_MEI157962
Value:encodings=<module 'encodings' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\base_library.zip\\encodings\\__init__.pyc'>
Value:pyimod03_ctypes=<module 'pyimod03_ctypes' from 'D:\\MIO\\PyInstaller\\loader\\pyimod03_ctypes.py'>
Value:pyimod04_pywin32=<module 'pyimod04_pywin32' from 'D:\\MIO\\PyInstaller\\loader\\pyimod04_pywin32.py'>
Value:entry=C:\Users\14337\AppData\Local\Temp\_MEI157962\__splash
Value:mmap=<module 'mmap' (built-in)>
Value:platform=<module 'platform' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\platform.pyc'>
Value:subprocess=<module 'subprocess' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\subprocess.pyc'>
Value:wraps=<function wraps at 0x07663EC8>
Value:AI_engine=<module 'AI_engine' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\AI_engine.pyc'>
Value:ext4=<module 'ext4' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\ext4.pyc'>
Value:load_window=<module 'load_window' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\load_window.pyc'>
Value:json=<module 'json' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\json\\__init__.pyc'>
Value:shlex=<module 'shlex' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\shlex.pyc'>
Value:time=<module 'time' (built-in)>
Value:tk=<module 'tkinter' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\__init__.pyc'>
Value:ConfigParser=<class 'configparser.ConfigParser'>
Value:openurl=<function open at 0x07E9A6A0>
Value:extra=<module 'extra' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\extra.pyc'>
Value:utils=<module 'utils' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\utils.pyc'>
Value:re=<module 're' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\base_library.zip\\re.pyc'>
Value:contextpatch=<module 'contextpatch' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\contextpatch.pyc'>
Value:fspatch=<module 'fspatch' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\fspatch.pyc'>
Value:symlink=<function symlink at 0x07EA5028>
Value:updaterutil=<class 'extra.updaterutil'>
Value:script2fs_context=<function script2fs_context at 0x07E9A4A8>
Value:cz=<function cz at 0x07E04808>
Value:jzxs=<function jzxs at 0x07E04970>
Value:v_code=<function v_code at 0x07E04778>
Value:gettype=<function gettype at 0x07D59610>
Value:findfile=<function findfile at 0x07E048E0>
Value:findfolder=<function findfolder at 0x07E04928>
Value:sdat2img=<class 'utils.sdat2img'>
Value:windnd=<module 'windnd' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\windnd\\__init__.pyc'>
Value:filedialog=<module 'tkinter.filedialog' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\filedialog.pyc'>
Value:zipfile=<module 'zipfile' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\zipfile.pyc'>
Value:BytesIO=<class '_io.BytesIO'>
Value:StringIO=<class '_io.StringIO'>
Value:machine=<function machine at 0x07881460>
Value:enum=<module 'enum' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\base_library.zip\\enum.pyc'>
Value:TclError=<class '_tkinter.TclError'>
Value:constants=<module 'tkinter.constants' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\constants.pyc'>
Value:NO=0
Value:FALSE=0
Value:OFF=0
Value:YES=1
Value:TRUE=1
Value:ON=1
Value:N=n
Value:S=s
Value:W=w
Value:E=e
Value:NW=nw
Value:SW=sw
Value:NE=ne
Value:SE=se
Value:NS=ns
Value:EW=ew
Value:NSEW=nsew
Value:CENTER=center
Value:NONE=none
Value:X=x
Value:Y=y
Value:BOTH=both
Value:LEFT=left
Value:TOP=top
Value:RIGHT=right
Value:BOTTOM=bottom
Value:RAISED=raised
Value:SUNKEN=sunken
Value:FLAT=flat
Value:RIDGE=ridge
Value:GROOVE=groove
Value:SOLID=solid
Value:HORIZONTAL=horizontal
Value:VERTICAL=vertical
Value:NUMERIC=numeric
Value:CHAR=char
Value:WORD=word
Value:BASELINE=baseline
Value:INSIDE=inside
Value:OUTSIDE=outside
Value:SEL=sel
Value:SEL_FIRST=sel.first
Value:SEL_LAST=sel.last
Value:END=end
Value:INSERT=insert
Value:CURRENT=current
Value:ANCHOR=anchor
Value:ALL=all
Value:NORMAL=normal
Value:DISABLED=disabled
Value:ACTIVE=active
Value:HIDDEN=hidden
Value:CASCADE=cascade
Value:CHECKBUTTON=checkbutton
Value:COMMAND=command
Value:RADIOBUTTON=radiobutton
Value:SEPARATOR=separator
Value:SINGLE=single
Value:BROWSE=browse
Value:MULTIPLE=multiple
Value:EXTENDED=extended
Value:DOTBOX=dotbox
Value:UNDERLINE=underline
Value:PIESLICE=pieslice
Value:CHORD=chord
Value:ARC=arc
Value:FIRST=first
Value:LAST=last
Value:BUTT=butt
Value:PROJECTING=projecting
Value:ROUND=round
Value:BEVEL=bevel
Value:MITER=miter
Value:MOVETO=moveto
Value:SCROLL=scroll
Value:UNITS=units
Value:PAGES=pages
Value:wantobjects=1
Value:TkVersion=8.6
Value:TclVersion=8.6
Value:READABLE=2
Value:WRITABLE=4
Value:EXCEPTION=8
Value:EventType=<enum 'EventType'>
Value:Event=<class 'tkinter.Event'>
Value:NoDefaultRoot=<function NoDefaultRoot at 0x07CFBCD0>
Value:Variable=<class 'tkinter.Variable'>
Value:StringVar=<class 'tkinter.StringVar'>
Value:IntVar=<class 'tkinter.IntVar'>
Value:DoubleVar=<class 'tkinter.DoubleVar'>
Value:BooleanVar=<class 'tkinter.BooleanVar'>
Value:mainloop=<function mainloop at 0x07CFBE38>
Value:getint=<class 'int'>
Value:getdouble=<class 'float'>
Value:getboolean=<function getboolean at 0x07D1E4F0>
Value:Misc=<class 'tkinter.Misc'>
Value:CallWrapper=<class 'tkinter.CallWrapper'>
Value:XView=<class 'tkinter.XView'>
Value:YView=<class 'tkinter.YView'>
Value:Wm=<class 'tkinter.Wm'>
Value:Tk=<class 'tkinter.Tk'>
Value:Tcl=<function Tcl at 0x07D1E538>
Value:Pack=<class 'tkinter.Pack'>
Value:Place=<class 'tkinter.Place'>
Value:Grid=<class 'tkinter.Grid'>
Value:BaseWidget=<class 'tkinter.BaseWidget'>
Value:Widget=<class 'tkinter.Widget'>
Value:Toplevel=<class 'tkinter.Toplevel'>
Value:Button=<class 'tkinter.Button'>
Value:Canvas=<class 'tkinter.Canvas'>
Value:Checkbutton=<class 'tkinter.Checkbutton'>
Value:Entry=<class 'tkinter.Entry'>
Value:Frame=<class 'tkinter.Frame'>
Value:Label=<class 'tkinter.Label'>
Value:Listbox=<class 'tkinter.Listbox'>
Value:Menu=<class 'tkinter.Menu'>
Value:Menubutton=<class 'tkinter.Menubutton'>
Value:Message=<class 'tkinter.Message'>
Value:Radiobutton=<class 'tkinter.Radiobutton'>
Value:Scale=<class 'tkinter.Scale'>
Value:Scrollbar=<class 'tkinter.Scrollbar'>
Value:Text=<class 'tkinter.Text'>
Value:OptionMenu=<class 'tkinter.OptionMenu'>
Value:Image=<module 'PIL.Image' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\PIL\\Image.pyc'>
Value:PhotoImage=<class 'tkinter.PhotoImage'>
Value:BitmapImage=<class 'tkinter.BitmapImage'>
Value:image_names=<function image_names at 0x07D22CD0>
Value:image_types=<function image_types at 0x07D2F220>
Value:Spinbox=<class 'tkinter.Spinbox'>
Value:LabelFrame=<class 'tkinter.LabelFrame'>
Value:PanedWindow=<class 'tkinter.PanedWindow'>
Value:ttk=<module 'tkinter.ttk' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\ttk.pyc'>
Value:dialog=<module 'tkinter.dialog' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\dialog.pyc'>
Value:commondialog=<module 'tkinter.commondialog' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\commondialog.pyc'>
Value:messagebox=<module 'tkinter.messagebox' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\messagebox.pyc'>
Value:simpledialog=<module 'tkinter.simpledialog' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\tkinter\\simpledialog.pyc'>
Value:rmtree=<function rmtree at 0x077C3340>
Value:copy=<function copy at 0x077C30B8>
Value:move=<function move at 0x077C33D0>
Value:requests=<module 'requests' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\requests\\__init__.pyc'>
Value:sv_ttk=<module 'sv_ttk' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\sv_ttk\\__init__.pyc'>
Value:ImageTk=<module 'PIL.ImageTk' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\PIL\\ImageTk.pyc'>
Value:imgextractor=<module 'imgextractor' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\imgextractor.pyc'>
Value:lpunpack=<module 'lpunpack' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\lpunpack.pyc'>
Value:mkdtboimg=<module 'mkdtboimg' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\mkdtboimg.pyc'>
Value:ozipdecrypt=<module 'ozipdecrypt' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\ozipdecrypt.pyc'>
Value:payload_dumper=<module 'payload_dumper' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\payload_dumper.pyc'>
Value:splituapp=<module 'splituapp' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\splituapp.pyc'>
Value:dti=<built-in function perf_counter>
Value:ofp_qc_decrypt=<module 'ofp_qc_decrypt' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\ofp_qc_decrypt.pyc'>
Value:ofp_mtk_decrypt=<module 'ofp_mtk_decrypt' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\ofp_mtk_decrypt.pyc'>
Value:editor=<module 'editor' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\editor.pyc'>
Value:yaml=<module 'yaml' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\yaml\\__init__.pyc'>
Value:opscrypto=<module 'opscrypto' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\opscrypto.pyc'>
Value:images=<module 'images' from 'C:\\Users\\14337\\AppData\\Local\\Temp\\_MEI157962\\images.pyc'>
Value:json_edit=<class '__main__.json_edit'>
Value:load_car=<class '__main__.load_car'>
Value:cartoon=<__main__.load_car object at 0x07E4F910>
Value:dev_null=<class '__main__.dev_null'>
Value:Tool=<class '__main__.Tool'>
Value:win=.
Value:start=0.8934166
Value:elocal=D:\MIO
Value:settings_file=D:\MIO\bin\setting.ini
Value:dn=PY_VAR0
Value:theme=PY_VAR1
Value:language=PY_VAR2
Value:tool_bin=D:\MIO\bin\Windows\AMD64\
Value:ModuleError=<class '__main__.ModuleError'>
Value:lang_utils=<class '__main__.lang_utils'>
Value:lang=<__main__.lang_utils object at 0x089347A8>
Value:load=<function load at 0x0893E658>
Value:error=<function error at 0x0893E730>
Value:welcome=<class '__main__.welcome'>
Value:set_utils=<class '__main__.set_utils'>
Value:settings=<__main__.set_utils object at 0x089347F0>
Value:re_folder=<function re_folder at 0x082373D0>
Value:un_dtbo=<function un_dtbo at 0x0893ED18>
Value:pack_dtbo=<function pack_dtbo at 0x0893EC88>
Value:logo_dump=<function logo_dump at 0x0893EBF8>
Value:logo_pack=<function logo_pack at 0x0893EB68>
Value:Process=<class '__main__.Process'>
Value:IconGrid=<class '__main__.IconGrid'>
Value:mpkman=<function mpkman at 0x0893EB20>
Value:Install_mpk=<class '__main__.Install_mpk'>
Value:packxx=<class '__main__.packxx'>
Value:dbkxyt=<function dbkxyt at 0x092E1388>
Value:packss=<class '__main__.packss'>
Value:packsuper=<function packsuper at 0x092E16E8>
Value:StdoutRedirector=<class '__main__.StdoutRedirector'>
Value:call=<function call at 0x092E1730>
Value:download_api=<function download_api at 0x092E1850>
Value:download_file=<function download_file at 0x092E1898>
Value:jboot=<function jboot at 0x092E1928>
Value:dboot=<function dboot at 0x092E19B8>
Value:packrom=<function packrom at 0x092E1A48>
Value:rdi=<function rdi at 0x092E1A90>
Value:input_=<function input_ at 0x092E1AD8>
Value:script2fs=<function script2fs at 0x092E1B20>
Value:unpackrom=<function unpackrom at 0x092E1BB0>
Value:rwork=<function rwork at 0x092E1BF8>
Value:unpack=<function unpack at 0x092E1C88>
Value:ask_win=<function ask_win at 0x092E1CD0>
Value:dirsize=<class '__main__.dirsize'>
Value:datbr=<function datbr at 0x092E1E38>
Value:mkerofs=<function mkerofs at 0x092E1E80>
Value:make_ext4fs=<function make_ext4fs at 0x092E1F10>
Value:mke2fs=<function mke2fs at 0x092E1F58>
Value:rmdir=<function rmdir at 0x092E5028>
Value:get_all_file_paths=<function get_all_file_paths at 0x092E5070>
Value:zip_file=<function zip_file at 0x092E50B8>
Value:pack_zip=<function pack_zip at 0x092E5190>
Value:dndfile=<function dndfile at 0x092E51D8>
Value:project_menu_utils=<class '__main__.project_menu_utils'>
Value:frame3=<class '__main__.frame3'>
Value:unpack_gui=<class '__main__.unpack_gui'>
Value:list_pls_plugin=<function mpkman.<locals>.list_pls at 0x092F10B8>
Value:unpackg=.!labelframe.!notebook.!frame2.!unpack_gui
Value:project_menu=.!labelframe.!notebook.!frame2.!project_menu_utils
Value:img2simg=<function img2simg at 0x092F1EC8>
Value:format_conversion=<class '__main__.format_conversion'>
Value:__warningregistry__={'version': 6}

Error File: C:\Users\14337\AppData\Local\Temp\_MEI157962\tool.py

Error Function: unpack

Function Args: ((['super'], 'img'), {})

Error Line:130

Reason: PermissionError(13, 'Permission denied')

**Comment by ColdWindScholar** [comment]
pls use the latest version
