### ISSUE TITLE
无法解包vivoromimg

### ISSUE THREAD

**Issue by nmmmea** [ColdWindScholar/MIO-KITCHEN-SOURCE#41]
vivo的system.img打包格式为system.img: Zstandard，无法解压
rom链接https://sysupwrrdl.vivo.com.cn/upgrade/oem/files/2024042303500724350486d1f2d122b664ec28ac100abf.zip

**Comment by ColdWindScholar** [comment]
oh, i will fix it

**Comment by ColdWindScholar** [comment]
Supported！Released 3.6.5
