### ISSUE TITLE
The work of the graph is super during unpacking and additional questions

### ISSUE THREAD

**Issue by MinDeaDBlood** [ColdWindScholar/MIO-KITCHEN-SOURCE#42]
1. When you select the super image graph when unpacking, the program freezes and does not issue any alerts. It is unclear whether it works or not. But there is an img graph, when selected, the same thing happens, but nothing freezes and all alerts are issued and it is clear that the program is working and not frozen. What is the point of having a super section when unpacking if it duplicates the functionality of the img graph?
2. Not all of the translation is available for translation into other languages. Some of the information alerts are in the small window on the left and some in the interface itself. And in some places, the description of functions is duplicated into other sections, the description of which should be different.That is, the translation of the interface is not completely separated for a separate description of all functions.  For example, "text9": "Functions" is one item, but translates the word functions that is above the word project and the list of images or folders in the packaging\unpacking window. But the translation of the function is not suitable for this window, it has a different loading meaning.
3. Is it possible to add a date decryption and AVB in the form of an on/off slider?
4. You have projects: D.N.A3, TIK. Are they better or worse than MIO-KITCHEN? For example, in TIK there is a decryption of the date section. Why is this feature not available in MIO-KITCHEN?
5. Is it possible to make a free choice of the graph when you switched the slider to the assembly? It is currently impossible to select an option there. For example, I would like the program to assemble the payload itself from the folders. But if you didn't unpack the payload, then this option is not available during the build, like the others - it's very inconvenient.
6. If I add system APCs or replace them completely, is it possible to make the program register them in permission and selinux if necessary? what is it for: for example, it is not possible to make a firmware port and I want to remove the apk from the stock images and replace them with another apk. thus, there is a chance to get a fully working stock-based firmware.I do not know if the APK will work normally in this case and how much sense it makes. I leave this idea to the developers of the program
7. Is it possible to make a slider for patching firmware settings, which will automatically do the firmware in RW
8. I would like to add the function of unpacking and packing the boot and vendor boot so that you can port kernels and recovery
9. Is it possible to add automatic porting of TWRP/OFOX/PBRP to the program? So that the program itself takes the necessary modules, drivers, all the necessary files to run and adds them to the recovery that the person wants to port

**Comment by ColdWindScholar** [comment]
what？

**Comment by ColdWindScholar** [comment]
Some logs？

**Comment by MinDeaDBlood** [comment]
> Some logs？

what logs do you need if, when selecting the unpack graph, the super program freezes and remains suspended without any information until it finishes the process. But why do we need this option if the img graph performs the same task and informs us about what is happening and does not hang indefinitely. Everything else is clearly described. logs are not needed here
