### ISSUE TITLE
AMLogic image support

### ISSUE THREAD

**Issue by kalehrl** [ColdWindScholar/MIO-KITCHEN-SOURCE#44]
Hi
I tried to unpack AMLogic image file but it is not supported.
Can you add AMLogic image support in your tool?
Thank you.

**Comment by ColdWindScholar** [comment]
ok, i will add

**Comment by ColdWindScholar** [comment]
can u give me a image as example?

**Comment by kalehrl** [comment]
Thank you.
Here are Android 9 images:
https://disk.yandex.ru/d/0I-hiUFf_9onSg
Android 11:
https://disk.yandex.ru/d/rkjSdcgUJW7Bkg

**Comment by kalehrl** [comment]
There are also Android images for Allwinner and Rockchip but they are a different matter.

**Comment by ColdWindScholar** [comment]
check our user group.

**Comment by kalehrl** [comment]
Sorry, but what user group?

**Comment by bt4ibwem8** [comment]
@ColdWindScholar 
Hi, did you add it? It seems not working, got this error:
```
Type:[unknown]
This file is not in a supported format, unknown
```
