### ISSUE TITLE
Error when trying to extract vendor.img with empty vendor file in it that it's some kind of unknown payload or idk

### ISSUE THREAD

**Issue by Dachoni03** [ColdWindScholar/MIO-KITCHEN-SOURCE#47]
I'm getting this error when try to extract vendor.img with empty vendor file in it.

![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/106074709/3bd9c457-6178-4936-89ac-52ce7805e6a0)

------------------
The error below
--------------------------------
Unpacking:vendor.img [erofs]
Unpack failed...
Success!

**Comment by ColdWindScholar** [comment]
give me the image
