### ISSUE TITLE
I found ponzy and some other viruses is this normal

### ISSUE THREAD

**Issue by Dachoni03** [ColdWindScholar/MIO-KITCHEN-SOURCE#49]
I hope these viruses to be used only for the images.

**Comment by ColdWindScholar** [comment]
where viruses？tell me? and u parsed them? give me ss please?

**Comment by yui-onanii** [comment]
> I hope these viruses to be used only for the images.

You can run the tool from source (which give you chance to review it before run), and delete `bin/Windows/AMD64/*.*`, collect these tool bins from elsewhere u trust instead

**Comment by yui-onanii** [comment]
afaik mio compiled most of these tools from source himself (some were compiled by his friends), some were downloaded from official sites
