### ISSUE TITLE
[erofs] Unpack Fail...

### ISSUE THREAD

**Issue by skvignesh15** [ColdWindScholar/MIO-KITCHEN-SOURCE#5]
Selected items:payload
Unpacking:payload
[EXTRACTING]: system
system:[162.xxxxx1]

Selected items:payload
Unpacking:system.img [erofs]
Unpack Fail...
Success!

**Comment by alone412** [comment]
> Selected items:payload Unpacking:payload [EXTRACTING]: system system:[162.xxxxx1]
> 
> Selected items:payload Unpacking:system.img [erofs] Unpack Fail... Success!

excute from c drive

**Comment by skvignesh15** [comment]
executed from c drive downloads folder only

**Comment by alone412** [comment]
Paste mio folder direct cdrive

**Comment by alone412** [comment]
> executed from c drive downloads folder only

Pase mio folder direct c drive

**Comment by ColdWindScholar** [comment]
Is there a space in the path?

**Comment by ColdWindScholar** [comment]
Can you provide a link?
