### ISSUE TITLE
error: make_directory: failed to allocate inode

### ISSUE THREAD

**Issue by alone412** [ColdWindScholar/MIO-KITCHEN-SOURCE#6]
error: make_directory: failed to allocate inode

loaded 574 fs_config entries
Creating filesystem with parameters:
Size: 7385088
Block size: 4096
Blocks per group: 32768
Inodes per group: 464
Inode size: 256
Journal blocks: 0
Label: my_region
Blocks: 1803
Block groups: 1
Reserved block group size: 7

**Comment by ColdWindScholar** [comment]
Use MKE2FS + E2FSDROID ?

**Comment by alone412** [comment]
> Use MKE2FS + E2FSDROID ?

No 

But trying both still same

**Comment by ColdWindScholar** [comment]
Size too less, so you need use KE2FS + E2FSDROID or add size_number
