### ISSUE TITLE
Samsung firmware system.img error when repack with windows version

### ISSUE THREAD

**Issue by long5436** [ColdWindScholar/MIO-KITCHEN-SOURCE#66]
How to reproduce the problem; unpack a working system img and repack it using the windows version the system will bootloop, but doing the same with the linux version does not have the issue. (firmware used is samsung S21FE)

**Comment by qlenlen** [comment]
It may be the problem of the binary mkfs.erofs, just use Linux instead.

**Comment by privacyguy123** [comment]
I am pretty sure there is no support for Samsung ODIN zips. Can it be added somehow like crb does it?

**Comment by ColdWindScholar** [comment]
give me the odin

> I am pretty sure there is no support for Samsung ODIN zips. Can it be added somehow like crb does it?

**Comment by privacyguy123** [comment]
https://xdaforums.com/t/patched-odin-3-13-1.3762572/

**Comment by ColdWindScholar** [comment]
wow？

**Comment by ColdWindScholar** [comment]
have u fixed them?
