### ISSUE TITLE
UI font is specified by itself

### ISSUE THREAD

**Issue by reindex-ot** [ColdWindScholar/MIO-KITCHEN-SOURCE#8]
There is a problem that free fonts that have been installed are automatically specified.
Japanese translation is provided, but the font is missing.
![UI](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/32851879/c058515f-94f1-4985-b290-1a96ab6dd43a)

**Comment by ookiineko** [comment]
see #51

**Comment by ookiineko** [comment]
@ColdWindScholar pls reopen, its just a workaround, not a real fix

**Comment by ookiineko** [comment]
sorry for confusion, but this issue seems to be a wontfix, it is related to user's system language, if system language is not Japanese, the default font will not contain Japanese character, and application might then fallback to any installed Japanese font

**Comment by ookiineko** [comment]
this turned out to be the cause:

https://github.com/rdbende/Sun-Valley-ttk-theme/blob/12ee4ff/sv_ttk/sv.tcl#L13-L20

**Comment by ookiineko** [comment]
seems like we should just override the font family manually, at least sv_ttk upstream said this

upstream related issue: https://github.com/rdbende/Sun-Valley-ttk-theme/issues/66

so i guess it should be fixed in #53
