### ISSUE TITLE
F2FS Repacking Problem

### ISSUE THREAD

**Issue by Mohegua** [ColdWindScholar/MIO-KITCHEN-SOURCE#89]
F2FS repacking with Samsung ROMs shows error after repacking on any images and on any Linux distributions.
For system.img, error message by MIO Kitchen is "Failed to pack system!".
It seems that the error occurs only with F2FS.

**Comment by ColdWindScholar** [comment]
its normal, if the image was cerated, you can ignore "Have a good dinner!" and the image is useable
