### ISSUE TITLE
Packing into super doesn't work

### ISSUE THREAD

**Issue by winbo-yml-exe** [ColdWindScholar/MIO-KITCHEN-SOURCE#90]
I made a HyperOS mod, but now when i try to pack it into a super image, this happens

> Welcome to the new MIO-KITCHEN
> This tool is free forever
> Startup took : 0.41805159999967145 Seconds
> lpmake I 11-06 16:54:31  1882 15212 builder.cpp:1093] [liblp]Partition mi_ext_a will resize from 0 bytes to 338436096 bytes
> lpmake I 11-06 16:54:31  1882 15212 builder.cpp:1093] [liblp]Partition product_a will resize from 0 bytes to 2597523456 bytes
> lpmake I 11-06 16:54:31  1882 15212 builder.cpp:1093] [liblp]Partition system_a will resize from 0 bytes to 824602624 bytes
> lpmake I 11-06 16:54:31  1882 15212 builder.cpp:1093] [liblp]Partition system_ext_a will resize from 0 bytes to 677531648 bytes
> lpmake I 11-06 16:54:31  1882 15212 builder.cpp:1093] [liblp]Partition vendor_a will resize from 0 bytes to 403722240 bytes
> lpmake E 11-06 16:54:32  1882 15212 images.cpp:461] [liblp]make temporary file failed: No such file or directory
> lpmake E 11-06 16:54:32  1882 15212 images.cpp:326] [liblp]Could not open image for partition: mi_ext_a

**Comment by ColdWindScholar** [comment]
may the image is sprase?

**Comment by ColdWindScholar** [comment]
convert the mi_ext to raw
