### ISSUE TITLE
compile linux dont work

### ISSUE THREAD

**Issue by gss200610** [ColdWindScholar/MIO-KITCHEN-SOURCE#92]
Traceback (most recent call last):
  File "tool.py", line 11, in <module>
  File "src/tool.py", line 4393, in init
  File "logging/__init__.py", line 2118, in basicConfig
  File "logging/__init__.py", line 1231, in __init__
  File "logging/__init__.py", line 1263, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/home/enrico/sources/MIO-KITCHEN-SOURCE/dist/bin/temp/20241118_15-40-29_rtVvdi.log'
[PYI-16170:ERROR] Failed to execute script 'tool' due to unhandled exception!

Linux enrico-VirtualBox 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

ubuntu 24.04. tryed, 22,04 zorin+ pops, dont work after compile

**Comment by winbo-yml-exe** [comment]
cd into the mio folder/dist/bin
mkdir temp
enjoy

**Comment by ColdWindScholar** [comment]
my mistake, i will fix , sorry

**Comment by ColdWindScholar** [comment]
fixed

**Comment by gss200610** [comment]
> fixed

I'll test it.We have another problem, your lpmake does not create the super if there is a partition with zero bytes in the folder, for example: mi_extb. I have lpmake fixed.If you want to talk to me on telegram, it's gss200610
