### ISSUE TITLE
erro when pack vendor boot in ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by gss200610** [ColdWindScholar/MIO-KITCHEN-SOURCE#94]
ERROR:2024-11-28 20:57:43,614:tool.py:root:Bugs
Traceback (most recent call last):
  File "tool.py", line 3261, in start_
  File "tkinter/__init__.py", line 2608, in destroy
AttributeError: 'Packxx' object has no attribute 'children'
INFO:2024-11-28 20:57:43,616:tool.py:root:['busybox', 'ash', '-c', 'find | sed 1d | /home/enrico/tools/MIO-KITCHEN-4.0.0-linux/bin/Linux/x86_64//cpio -H newc -R 0:0 -o -F ../ramdisk-new.cpio']
INFO:2024-11-28 20:57:43,703:tool.py:root:Segmentation fault (core dumped)
INFO:2024-11-28 20:57:43,705:tool.py:root:['magiskboot', 'compress=lz4_legacy', 'ramdisk-new.cpio']
INFO:2024-11-28 20:57:43,707:tool.py:root:fopen ramdisk-new.cpio failed with 2: No such file or directory
DEBUG:2024-11-28 20:57:43,742:PngImagePlugin.py:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:2024-11-28 20:57:43,742:PngImagePlugin.py:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:2024-11-28 20:57:43,742:PngImagePlugin.py:PIL.PngImagePlugin:STREAM b'IDAT' 54 8192
ERROR:2024-11-28 20:58:06,368:tool.py:root:Bugs
Traceback (most recent call last):
  File "tool.py", line 187, in stop
  File "tkinter/__init__.py", line 871, in after_cancel
RuntimeError: main thread is not in main loop
ERROR:2024-11-28 20:58:07,370:tool.py:root:Bugs
Traceback (most recent call last):
  File "tool.py", line 187, in stop
  File "tkinter/__init__.py", line 871, in after_cancel
RuntimeError: main thread is not in main loop
ERROR:2024-11-28 20:58:08,373:tool.py:root:Bugs
Traceback (most recent call last):

**Comment by ColdWindScholar** [comment]
give me the image pls

**Comment by gss200610** [comment]
Do you have telegram?

**Comment by ColdWindScholar** [comment]
**https://t.me/mio_android_kitchen_group**
